// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iohauqhunkuqvwntovcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvaGF1cWh1bmt1cXZ3bnRvdmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDI3MzMsImV4cCI6MjA2MDYxODczM30.i7P8-iO54PAb_sqOp4XLtKbPpl8BMCgWIn89RqzEfj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);